export const AUTH_CONSTRAINTS = {
  SEND_OTP_COUNT_TTL: 3600, // 1시간
  SEND_OTP_BLOCKED_TTL: 3600, // 1시간
  SEND_OTP_MAX_COUNT: 5,
  OTP_TTL: 180, // 3분
  VERIFICATION_COUNT_TTL: 3600, // 1시간
  VERIFICATION_BLOCKED_TTL: 3600, // 1시간
  VERIFICATION_MAX_COUNT: 5,
};
