import * as Joi from 'joi';

export const RAG_KEY = {
  RAG_PINECONE_API_KEY: 'RAG_PINECONE_API_KEY',
  RAG_PINECONE_INDEX_NAME: 'RAG_PINECONE_INDEX_NAME',
  RAG_PINECONE_USER_NAMESPACE: 'RAG_PINECONE_USER_NAMESPACE',
  RAG_PINECONE_PARTICIPANT_NAMESPACE: 'RAG_PINECONE_PARTICIPANT_NAMESPACE',
  RAG_OPNEAI_API_KEY: 'RAG_OPNEAI_API_KEY',
  RAG_OPENAI_EMBEDDING_MODEL_NAME: 'RAG_OPENAI_EMBEDDING_MODEL_NAME',
  RAG_OPENAI_CHAT_MODEL_NAME: 'RAG_OPENAI_CHAT_MODEL_NAME',
} as const;

export const RAG_KEY_VALIDATOR = {
  RAG_PINECONE_API_KEY: Joi.string().required(),
  RAG_PINECONE_INDEX_NAME: Joi.string().required(),
  RAG_PINECONE_USER_NAMESPACE: Joi.string().required(),
  RAG_PINECONE_PARTICIPANT_NAMESPACE: Joi.string().required(),
  RAG_OPNEAI_API_KEY: Joi.string().required(),
  RAG_OPENAI_EMBEDDING_MODEL_NAME: Joi.string().required(),
  RAG_OPENAI_CHAT_MODEL_NAME: Joi.string().required(),
} as const;
