export const EVENT_CONSTRAINTS = {
  TITLE_MIN_LENGTH: 1,
  TITLE_MAX_LENGTH: 100,
  DESCRIPTION_MIN_LENGTH: 1,
  DESCRIPTION_MAX_LENGTH: 5000,
  RANDOM_HANDLE_MIN_LENGTH: 6,
  // RANDOM_HANDLE_MAX_LENGTH: 20,
  CUSTOM_HANDLE_MIN_LENGTH: 3,
  CUSTOM_HANDLE_MAX_LENGTH: 50,
};
