export enum UserExceptionEnum {
  UserNotFound = 'G10001',
  UserAlreadyExist = 'G10002',
  ThirdPartyAccountNotFound = 'G10003',
  ThirdPartyAccountAlreadyExist = 'G10004',
  UserDeviceNotFound = 'G10005',
  UserDeviceAlreadyExist = 'G10006',
  LikeNotFound = 'G10007',
  LikeAlreadyExist = 'G10008',
  LikeTargetUserNotFound = 'G10009',
  CannotLikeSelf = 'G10010',
  CannotUnlikeSelf = 'G10011',
  AlreadyUsedHandle = 'G10012',
  AlreadyUsedEmail = 'G10013',
  AlreadyUsedSocialType = 'G10014',
  AlreadyUsedWebsiteTitle = 'G10015',
}

export enum UserExceptionMessage {
  UserNotFound = '유저를 찾을 수 없습니다.',
  UserAlreadyExist = '이미 존재하는 유저입니다.',
  ThirdPartyAccountNotFound = '소셜 계정을 찾을 수 없습니다.',
  ThirdPartyAccountAlreadyExist = '이미 존재하는 소셜 계정입니다.',
  UserDeviceNotFound = '디바이스를 찾을 수 없습니다.',
  UserDeviceAlreadyExist = '이미 존재하는 디바이스입니다.',
  LikeNotFound = 'Like가 존재하지 않습니다.',
  LikeAlreadyExist = '이미 Like가 존재합니다.',
  LikeTargetUserNotFound = '대상 유저를 찾을 수 없습니다.',
  CannotLikeSelf = '자신을 Like할 수 없습니다.',
  CannotUnlikeSelf = '자신을 Unlike할 수 없습니다.',
  AlreadyUsedHandle = '이미 사용중인 핸들입니다.',
  AlreadyUsedEmail = '이미 사용중인 이메일입니다.',
  AlreadyUsedSocialType = '이미 사용중인 소셜 타입입니다.',
  AlreadyUsedWebsiteTitle = '이미 사용중인 웹사이트 타이틀입니다.',
}
